### ISSUE TITLE
[feature request] One line for one tab

### ISSUE THREAD

**Issue by Golddouble** [gyu-don/move-to-window#1]
If I click on the icon, I get a list with all tabs in a particular window. If the links are long, then the link is distributed between two or more lines.

So my suggestion is to make a setting, that allows the user to make the dialog box bigger (broader), so that the whole link can be placed in one line.

Or an alternative would be to use only one line for one tab- link, but cut off it, if it has not the place in one line. Then when the user holds the mouse button over the tab- link it can be showed as a full link.

**Comment by gyu-don** [comment]
Thank you for your comment. I updated to use only one line for one tab. I may implement resizing panel and/or showing full text, but I'm not sure if it makes good user experience or not.

**Comment by Golddouble** [comment]
Thank you for implementing this.
